---
- name: read additional certificates from -extra-ca-certs directory
  slurp:
      src: "{{ item }}"

  with_fileglob:
      - "{{ inventory_dir }}/{{ kube_cluster_name }}-extra-ca-certs/*"
  register: extra_cas
  delegate_to: localhost
  connection: local

- debug:
    var: extra_cas
