---
- name: rebooting nodes
  vars:
    - ansible_python_interpreter: /home/core/pypy/bin/python
    - ansible_host: "{{ current_node.ip_address }}"
  shell: sleep 5 && reboot &
  sudo: yes
  args:
      executable: /bin/bash
  async: 10
  poll: 0


- name: waiting for nodes to go down
  local_action:
      module: wait_for
      host: "{{ inventory_hostname }}"
      port: 22
      delay: 1
      timeout: 60
      state: stopped

- name: waiting for nodes to come back
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
      timeout=60
- name: wait some time to let the server rejoin the etcd cluster
  pause: seconds={{ unsafe_reboot_delay|default("300") }}
