---
- name: copy CA certificate
  local_action:
    module: copy
    src: "{{ inventory_dir }}/{{ kube_cluster_name }}-ca/ca.pem"
    dest:  "{{ lookup('env','HOME') }}/.kube/certs/{{ kube_cluster_name }}-ca.pem"
  run_once: true
  delegate_to: 127.0.0.1
  connection: local

- name: copy KubectlAdmin certificate
  local_action:
    module: copy
    src: "{{ inventory_dir }}/{{ kube_cluster_name }}-ca/keys/KubectlAdmin.host.pem"
    dest:  "{{ lookup('env','HOME') }}/.kube/certs/"
  run_once: true
  delegate_to: 127.0.0.1
  connection: local

- name: copy KubectlAdmin key
  local_action:
    module: copy
    src: "{{ inventory_dir }}/{{ kube_cluster_name }}-ca/keys/KubectlAdmin.host-key.pem"
    dest:  "{{ lookup('env','HOME') }}/.kube/certs/"
  run_once: true
  delegate_to: 127.0.0.1
  connection: local

- name: configure kubectl
  shell: |
     {{ lookup('env','HOME') }}/bin/kubectl config set-cluster {{ kube_cluster_name }} --server=https://{{ kube_master_dns_name|default(kube_master_ip)}}:6443 --certificate-authority={{ lookup('env','HOME') }}/.kube/certs/{{ kube_cluster_name }}-ca.pem
     {{ lookup('env','HOME') }}/bin/kubectl config set-credentials {{ kube_cluster_name }}-admin --certificate-authority={{ lookup('env','HOME') }}/.kube/certs/{{ kube_cluster_name }}-ca.pem --client-key={{ lookup('env','HOME') }}/.kube/certs/KubectlAdmin.host-key.pem --client-certificate={{ lookup('env','HOME') }}/.kube/certs/KubectlAdmin.host.pem
     {{ lookup('env','HOME') }}/bin/kubectl config set-context {{ kube_cluster_name }} --cluster={{ kube_cluster_name }} --user={{ kube_cluster_name }}-admin
     {{ lookup('env','HOME') }}/bin/kubectl config use-context {{ kube_cluster_name }}
  run_once: true
  delegate_to: 127.0.0.1
  connection: local
