---
- name: wait for kubernetes master to come up
  delegate_to: localhost
  connection: local
  when: inventory_hostname in groups['kubernetes-master']
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 6443
    timeout: 600

- name: kubectl checksum
  local_action:
     module: shell
     args: "sha256sum ~/bin/kubectl  | awk '{ print $1}'"
  run_once: yes
  register: current_kubectl_checksum
  changed_when: false

- name: download kubectl
  local_action:
     module: get_url
     url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes_version }}/bin/linux/amd64/kubectl"
     dest: ~/bin/
     sha256sum: "{{ kubectl_checksum }}"
     mode: 0770
  run_once: yes
  when: kubectl_checksum != current_kubectl_checksum.stdout
